app:
  name: 'L0_Order'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  pool_max: 2
  url: 'postgres://postgres:postgres@localhost:5432/postgres?pool_max_conns=10'


rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'